name = "caveful_games/limesignal"
version = "0.1.6"
description = "A fork of LemonSignal with additional features added"
authors = ["Aspecky", "Sona", "jiwonz"]
repository = "https://github.com/CavefulGames/LimeSignal"
license = "MIT"
includes = [
    "src",
    "LICENSE.md",
	"README.md"
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
